# Generated by Django 4.2 on 2024-06-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='tread',
            new_name='thread',
        ),
    ]
